name: ${DIRNAME} dir pull request path test

on:
  push:
    paths:
      - ${DIRNAME}/**
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    stesps:
      run: echo "This is test"

